const { auth } = require('../middlewares/auth.middleware')
const { masterAccessRouter } = require('../routes/master-access.routes')
const { masterPositionRouter } = require('../routes/master-position.routes')
const { masterDepartmentRouter } = require('../routes/master-department.routes')
const { masterEmployeeRouter } = require('../routes/master-employee.routes')
const { masterUserRouter } = require('../routes/master-user.routes')
const { masterRouteAccessRouter } = require('../routes/master-routeaccess.routes')
const { masterWalletRouter } = require('../routes/master-wallet.routes')
const { masterDistrictRouter } = require('../routes/master-district.routes')
const { masterModeOfTransportationRouter } = require('../routes/master-modeoftransportation.routes')
const { masterParticularsRouter } = require('../routes/master-particulars.routes')
const { budgetBudgetRouter } = require('../routes/budget-budget.routes')
const { revolvingFundRouter } = require('../routes/revolving-fund.routes')
const { cashDisbursementRouter } = require('../routes/cash-disbursement.routes')
const { cashRequestRouter } = require('../routes/cash-request.routes')
const { liquidationRouter } = require('../routes/liquidation-liquidation.routes')
const { redFlagRouter } = require('../routes/red-flag.routes')
const { synchronizeRouter } = require('../routes/synchronize.routes')

const initRoutes = (app) => {
  //app.use(auth)
  app.use('/master-access', masterAccessRouter)
  app.use('/master-position', masterPositionRouter)
  app.use('/master-department', masterDepartmentRouter)
  app.use('/master-employee', masterEmployeeRouter)
  app.use('/master-user', masterUserRouter)
  app.use('/master-routeaccess', masterRouteAccessRouter)
  app.use('/master-wallet', masterWalletRouter)
  app.use('/master-district', masterDistrictRouter)
  app.use('/master-modeoftransportation', masterModeOfTransportationRouter)
  app.use('/master-particulars', masterParticularsRouter)
  app.use('/budget-budget', budgetBudgetRouter)
  app.use('/revolving-fund', revolvingFundRouter)
  app.use('/cash-disbursement', cashDisbursementRouter)
  app.use('/cash-request', cashRequestRouter)
  app.use('/liquidation', liquidationRouter)
  app.use('/red-flag', redFlagRouter)
  app.use('/synchronize', synchronizeRouter)
}

module.exports = { initRoutes }
